export default {
  PAGE_SIZE: 15,
  ROUTE_GROUPS: {
    LOGIN: "LOGIN",
    BENS_PATRIMONIO: "BENS_PATRIMONIO",
    GESTAO_FINANCEIRO: "GESTAO_FINANCEIRO",
  },
  ACOES: {
    CADASTRAR_BEM: "CADASTRAR_BEM",
    EDITAR_BEM: "EDITAR_BEM",
    LISTAR_BEM: "LISTAR_BEM",
    VISUALIZAR_BEM: "VISUALIZAR_BEM",
    DOWNLOAD_BEM: "DOWNLOAD_BEM",
    CANCELAR_BEM: "CANCELAR_BEM",
    CADASTRAR_VALIDACAO_BEM: "CADASTRAR_VALIDACAO_BEM",
    EDITAR_VALIDACAO_BEM: "EDITAR_VALIDACAO_BEM",
    LISTAR_VALIDACAO_BEM: "LISTAR_VALIDACAO_BEM",
    VISUALIZAR_VALIDACAO_BEM: "VISUALIZAR_VALIDACAO_BEM",
    UPGRADE_MANUTENCAO: "UPGRADE_MANUTENCAO",
    ENCERRAMENTO_MANUTENCAO: "ENCERRAMENTO_MANUTENCAO",
  },
};
